### PR TITLE
feat: implement likes & dislikes with return youtube dislike api

### LINKED ISSUE #15: Clicking "More Videos" on a video's more info causes an internal error.
No clue if I should be posting it here, but i'm using this repo.
I am running this through docker, and connecting from an iPhone 3G running iOS 4.2.1 thru the classic youtube app.
No clue if ios 4.2.1 is actually supported but oh well.

```ERROR:main:Exception on /feeds/api/videos/Twn_4AW0M6U/related [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tuberepair-python/api/video.py", line 222, in get_suggested
    return get.template('classic/search.jinja2',{
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tuberepair-python/modules/get.py", line 53, in template
    output = t.render(render_data)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/dist-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "templates/classic/search.jinja2", line 23, in top-level template code
    <published>{{unix(info['published'])}}</published>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tuberepair-python/modules/get.py", line 16, in unix
    return datetime.fromtimestamp(int(unix)).isoformat() + '.000Z'
                                  ^^^^^^^^^
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'published'```

### PR DESCRIPTION
**Pull request by Preloading**
This PR implements dislikes and likes for YouTube clients thought the YouTube dislike api. I have tested it on Classic YouTube, so I might have have missed something on the app YouTube. It also fixes #15, since return YouTube dislikes api gives the date the video was created. 

I have added some fallback code if we are ratelimited, etc. Also later, it would probably be beneficial to add a way to disable this to avoid slamming the API and getting constantly limited.

### CODE REVIEW

**Comment by SGR21gtb** [comment]
Can you give me a proof to see if it's true or not? Yes I left the community so no hate or scare

**Comment by SGR21gtb** [comment]
And maybe you could add channel banners and activity (uploads only) to make it seem better

**Comment by kevinf100** [comment]
Will not be merged. API limits to low for how much traffic we currently get.
I've tested this and used this privately and scrapped it due to the 100 a minute/ 10000 a day API limits.

**Comment by Preloading** [comment]
Alright, understandable

**Comment by mrkrabs206** [comment]
> Will not be merged. API limits to low for how much traffic we currently get. I've tested this and used this privately and scrapped it due to the 100 a minute/ 10000 a day API limits.

Sad

**Comment by mrkrabs206** [comment]
Is there alternative

**Pull request closed without merging**
